name: "Config Environment"
on:
  workflow_call:
    outputs:
      current_env:
        description: "Current Environment"
        value: ${{ jobs.config.outputs.current_env}}
jobs:
  config:
    runs-on: [self-hosted, linux]
    outputs:
      current_env: ${{ steps.setenv.outputs.current_env }}
    steps:
      - id: setenv
        run: |
          if [ ${{github.ref_name}} == *"production"* ]
          then
            echo "current_env=Production" >> $GITHUB_OUTPUT
          elif [ ${{github.ref_name}} == *"development"* ]
          then
            echo "current_env=Development" >> $GITHUB_OUTPUT
          fi
